In [1]:
import pandas as pd
from pathlib import Path

print("Student Performance Prediction System")
print("Day 40: Model Training Preparation")

Student Performance Prediction System
Day 40: Model Training Preparation

In [2]:
root = Path(r"C:\Internship_project")
files = list(root.rglob("day39_analyzed_student_features.csv"))

if files:
    df = pd.read_csv(files[0])
    print("Dataset loaded:", files[0])
    print("Shape:", df.shape)
    display(df.head())
else:
    print("Dataset not found. Check Day 39 CSV file.")

Dataset loaded: C:\Internship_project\Data\day39_analyzed_student_features.csv
Shape: (1, 4)

   study_hours  attendance  previous_score  assignments_completed
0            6          90              78                      9

In [3]:
features = [
    "study_hours",
    "attendance",
    "previous_score",
    "assignments_completed"
]

available_features = [
    col for col in features if col in df.columns
]

X = df[available_features]

print("Input features:", available_features)
print("Feature shape:", X.shape)
display(X.head())

Input features: ['study_hours', 'attendance', 'previous_score', 'assignments_completed']
Feature shape: (1, 4)

   study_hours  attendance  previous_score  assignments_completed
0            6          90              78                      9

In [4]:
target = "predicted_performance"

if target in df.columns:
    print("Target column found:", target)
    print(df[target].value_counts(dropna=False))
else:
    print("Target column not found.")

Target column not found.

In [7]:
if target in df.columns:
    print("Target data type:", df[target].dtype)
    print("Unique target values:", df[target].nunique())
    print("Missing target values:", df[target].isnull().sum())

    print("\nImportant:")
    print("Confirm whether this column contains actual outcomes")
    print("or predictions generated by an earlier model.")

In [8]:
feature_report = pd.DataFrame({
    "Feature": available_features,
    "Data Type": [df[col].dtype for col in available_features],
    "Missing Values": [
        df[col].isnull().sum() for col in available_features
    ]
})

feature_report.to_csv(
    "day40_feature_preparation_report.csv",
    index=False
)

display(feature_report)
print("Feature report saved!")

                 Feature Data Type  Missing Values
0            study_hours     int64               0
1             attendance     int64               0
2         previous_score     int64               0
3  assignments_completed     int64               0

Feature report saved!

In [9]:
X.to_csv("day40_prepared_student_features.csv", index=False)

print("Prepared features saved successfully!")
print("Records:", len(X))
print("Features:", len(X.columns))

Prepared features saved successfully!
Records: 1
Features: 4

In [10]:
print("Project: Student Performance Prediction System")
print("Day 40: Model Training Preparation")
print("Prepared Features:", len(available_features))
print("Dataset Records:", len(df))
print("Day 40 completed successfully!")

Project: Student Performance Prediction System
Day 40: Model Training Preparation
Prepared Features: 4
Dataset Records: 1
Day 40 completed successfully!