In [3]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [5]:
data = {
    "Study_Hours": [1, 2, 3, 4, 5, 6, 7, 8],
    "Attendance": [60, 65, 70, 75, 80, 85, 90, 95],
    "Previous_Marks": [45, 50, 55, 60, 68, 75, 82, 90],
    "Result": ["Fail", "Fail", "Fail", "Pass", "Pass", "Pass", "Pass", "Pass"]
}

df = pd.DataFrame(data)

df

   Study_Hours  Attendance  Previous_Marks Result
0            1          60              45   Fail
1            2          65              50   Fail
2            3          70              55   Fail
3            4          75              60   Pass
4            5          80              68   Pass
5            6          85              75   Pass
6            7          90              82   Pass
7            8          95              90   Pass

In [7]:
df["Result"] = df["Result"].map({
    "Fail": 0,
    "Pass": 1
})

df

   Study_Hours  Attendance  Previous_Marks  Result
0            1          60              45     NaN
1            2          65              50     NaN
2            3          70              55     NaN
3            4          75              60     NaN
4            5          80              68     NaN
5            6          85              75     NaN
6            7          90              82     NaN
7            8          95              90     NaN

In [9]:
X = df[["Study_Hours", "Attendance", "Previous_Marks"]]
y = df["Result"]

print("Features:")
print(X)

print("\nTarget:")
print(y)

Features:
   Study_Hours  Attendance  Previous_Marks
0            1          60              45
1            2          65              50
2            3          70              55
3            4          75              60
4            5          80              68
5            6          85              75
6            7          90              82
7            8          95              90

Target:
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
Name: Result, dtype: float64

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42
)

print("Training data:")
print(X_train)

print("\nTesting data:")
print(X_test)

print("\nTraining target:")
print(y_train)

print("\nTesting target:")
print(y_test)

Training data:
   Study_Hours  Attendance  Previous_Marks
0            1          60              45
7            8          95              90
2            3          70              55
4            5          80              68
3            4          75              60
6            7          90              82

Testing data:
   Study_Hours  Attendance  Previous_Marks
1            2          65              50
5            6          85              75

Training target:
0   NaN
7   NaN
2   NaN
4   NaN
3   NaN
6   NaN
Name: Result, dtype: float64

Testing target:
1   NaN
5   NaN
Name: Result, dtype: float64

In [19]:
model = LogisticRegression()

print("Logistic Regression model created!")

Logistic Regression model created!

In [27]:
print("Training target values:")
print(y_train.value_counts())

Training target values:
Series([], Name: count, dtype: int64)

In [29]:
data = {
    "Study_Hours": [1, 2, 3, 4, 5, 6, 7, 8],
    "Attendance": [60, 65, 70, 75, 80, 85, 90, 95],
    "Previous_Marks": [45, 50, 55, 60, 68, 75, 82, 90],
    "Result": [0, 0, 0, 1, 1, 1, 1, 1]
}

df = pd.DataFrame(data)

print(df)
print("\nShape:", df.shape)

   Study_Hours  Attendance  Previous_Marks  Result
0            1          60              45       0
1            2          65              50       0
2            3          70              55       0
3            4          75              60       1
4            5          80              68       1
5            6          85              75       1
6            7          90              82       1
7            8          95              90       1

Shape: (8, 4)

In [31]:
X = df[["Study_Hours", "Attendance", "Previous_Marks"]]
y = df["Result"]

print("X shape:", X.shape)
print("y shape:", y.shape)
print("\ny values:")
print(y)

X shape: (8, 3)
y shape: (8,)

y values:
0    0
1    0
2    0
3    1
4    1
5    1
6    1
7    1
Name: Result, dtype: int64

In [33]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42
)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

print("\nTraining target values:")
print(y_train)

X_train shape: (6, 3)
X_test shape: (2, 3)
y_train shape: (6,)
y_test shape: (2,)

Training target values:
0    0
7    1
2    0
4    1
3    1
6    1
Name: Result, dtype: int64

In [35]:
model = LogisticRegression()

model.fit(X_train, y_train)

print("Model training completed!")

Model training completed!

In [37]:
y_pred = model.predict(X_test)

print("Predicted Results:")
print(y_pred)

Predicted Results:
[0 1]

In [39]:
comparison = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})

print(comparison)

   Actual  Predicted
0       0          0
1       1          1

In [41]:
accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:", accuracy)
print("Accuracy Percentage:", accuracy * 100, "%")

Model Accuracy: 1.0
Accuracy Percentage: 100.0 %

In [43]:
new_student = pd.DataFrame({
    "Study_Hours": [5],
    "Attendance": [82],
    "Previous_Marks": [70]
})

prediction = model.predict(new_student)

if prediction[0] == 1:
    print("Predicted Result: Pass")
else:
    print("Predicted Result: Fail")

Predicted Result: Pass

In [45]:
probability = model.predict_proba(new_student)

print("Fail Probability:", probability[0][0])
print("Pass Probability:", probability[0][1])

Fail Probability: 4.0681861701363786e-05
Pass Probability: 0.9999593181382986

In [46]:
print("Day 10 Logistic Regression completed!")
print("Model: Logistic Regression")
print("Task: Pass/Fail Classification")
print("Features: Study_Hours, Attendance, Previous_Marks")
print("Target: Result")
print("New student prediction completed.")

Day 10 Logistic Regression completed!
Model: Logistic Regression
Task: Pass/Fail Classification
Features: Study_Hours, Attendance, Previous_Marks
Target: Result
New student prediction completed.