In [3]:
import pandas as pd

In [5]:
data = {
    "Name": ["Sita", "Gita", "Raju", "Rani", "Amit", "Rahul", "Priya", "Kiran"],
    "Study_Hours": [2, 4, 1, 5, 3, 6, 4, 2],
    "Attendance": [70, 85, 60, 95, 80, 90, 88, 72],
    "Previous_Marks": [65, 75, 50, 90, 70, 92, 84, 68]
}

df = pd.DataFrame(data)

df

    Name  Study_Hours  Attendance  Previous_Marks
0   Sita            2          70              65
1   Gita            4          85              75
2   Raju            1          60              50
3   Rani            5          95              90
4   Amit            3          80              70
5  Rahul            6          90              92
6  Priya            4          88              84
7  Kiran            2          72              68

In [7]:
X = df[["Study_Hours", "Attendance", "Previous_Marks"]]

X

   Study_Hours  Attendance  Previous_Marks
0            2          70              65
1            4          85              75
2            1          60              50
3            5          95              90
4            3          80              70
5            6          90              92
6            4          88              84
7            2          72              68

In [9]:
df["Final_Marks"] = [68, 78, 55, 94, 74, 95, 88, 71]

y = df["Final_Marks"]

y

0    68
1    78
2    55
3    94
4    74
5    95
6    88
7    71
Name: Final_Marks, dtype: int64

In [11]:
print("Features (X):")
print(X)

print("\nTarget (y):")
print(y)

Features (X):
   Study_Hours  Attendance  Previous_Marks
0            2          70              65
1            4          85              75
2            1          60              50
3            5          95              90
4            3          80              70
5            6          90              92
6            4          88              84
7            2          72              68

Target (y):
0    68
1    78
2    55
3    94
4    74
5    95
6    88
7    71
Name: Final_Marks, dtype: int64

In [13]:
print("X shape:", X.shape)

X shape: (8, 3)

In [17]:
print("y shape:", y.shape)

y shape: (8,)

In [19]:
import sklearn
print("Scikit-learn is working!")

Scikit-learn is working!

In [21]:
from sklearn.model_selection import train_test_split

X = df[["Study_Hours", "Attendance", "Previous_Marks"]]

df["Final_Marks"] = [68, 78, 55, 94, 74, 95, 88, 71]

y = df["Final_Marks"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42
)

print("Data split successfully!")

Data split successfully!

In [23]:
print("X_train:")
print(X_train)

print("\ny_train:")
print(y_train)

X_train:
   Study_Hours  Attendance  Previous_Marks
0            2          70              65
7            2          72              68
2            1          60              50
4            3          80              70
3            5          95              90
6            4          88              84

y_train:
0    68
7    71
2    55
4    74
3    94
6    88
Name: Final_Marks, dtype: int64

In [25]:
print("X_test:")
print(X_test)

print("\ny_test:")
print(y_test)

X_test:
   Study_Hours  Attendance  Previous_Marks
1            4          85              75
5            6          90              92

y_test:
1    78
5    95
Name: Final_Marks, dtype: int64

In [26]:
print("Training data:", len(X_train))
print("Testing data:", len(X_test))

Training data: 6
Testing data: 2