In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [6]:
data = {
    "Name": ["Sita", "Gita", "Raju", "Rani", "Amit", "Rahul", "Priya", "Kiran"],
    "Study_Hours": [2, 4, 1, 5, 3, 6, 4, 2],
    "Attendance": [70, 85, 60, 95, 80, 90, 88, 72],
    "Previous_Marks": [65, 75, 50, 90, 70, 92, 84, 68],
    "Final_Marks": [68, 78, 55, 92, 74, 95, 88, 70]
}

df = pd.DataFrame(data)

df

    Name  Study_Hours  Attendance  Previous_Marks  Final_Marks
0   Sita            2          70              65           68
1   Gita            4          85              75           78
2   Raju            1          60              50           55
3   Rani            5          95              90           92
4   Amit            3          80              70           74
5  Rahul            6          90              92           95
6  Priya            4          88              84           88
7  Kiran            2          72              68           70

In [8]:
X = df[["Study_Hours", "Attendance", "Previous_Marks"]]

y = df["Final_Marks"]

print("Features:")
print(X)

print("\nTarget:")
print(y)

Features:
   Study_Hours  Attendance  Previous_Marks
0            2          70              65
1            4          85              75
2            1          60              50
3            5          95              90
4            3          80              70
5            6          90              92
6            4          88              84
7            2          72              68

Target:
0    68
1    78
2    55
3    92
4    74
5    95
6    88
7    70
Name: Final_Marks, dtype: int64

In [12]:
print(df.columns)

Index(['Name', 'Study_Hours', 'Attendance', 'Previous_Marks', 'Final_Marks'], dtype='str')

In [14]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training data:")
print(X_train)

print("\nTesting data:")
print(X_test)

print("\nTraining target:")
print(y_train)

print("\nTesting target:")
print(y_test)

Training data:
   Study_Hours  Attendance  Previous_Marks
0            2          70              65
7            2          72              68
2            1          60              50
4            3          80              70
3            5          95              90
6            4          88              84

Testing data:
   Study_Hours  Attendance  Previous_Marks
1            4          85              75
5            6          90              92

Training target:
0    68
7    70
2    55
4    74
3    92
6    88
Name: Final_Marks, dtype: int64

Testing target:
1    78
5    95
Name: Final_Marks, dtype: int64

In [16]:
model = LinearRegression()

print("Model created successfully!")

Model created successfully!

In [18]:
model.fit(X_train, y_train)

print("Model training completed!")

Model training completed!

In [20]:
print("Coefficients:")
print(model.coef_)

print("\nIntercept:")
print(model.intercept_)

Coefficients:
[0.90624277 0.13445087 0.7449711 ]

Intercept:
8.495260115606868

In [22]:
y_pred = model.predict(X_test)

print("Predicted Final Marks:")
print(y_pred)

Predicted Final Marks:
[79.42138728 94.57063584]

In [24]:
comparison = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})

comparison

   Actual  Predicted
0      78  79.421387
1      95  94.570636

In [26]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE: 0.9253757225433361
MSE: 1.1023476962143612
RMSE: 1.049927471882873
R2 Score: 0.9847425924399397

In [28]:
new_student = pd.DataFrame({
    "Study_Hours": [5],
    "Attendance": [90],
    "Previous_Marks": [85]
})

predicted_marks = model.predict(new_student)

print("Predicted Final Marks:", predicted_marks[0])

Predicted Final Marks: 88.44959537572257

In [29]:
print("Day 8 Multiple Linear Regression completed!")
print("The model was trained using Study_Hours, Attendance, and Previous_Marks.")
print("The model predicted Final_Marks for a new student.")
print("R2 Score:", r2)

Day 8 Multiple Linear Regression completed!
The model was trained using Study_Hours, Attendance, and Previous_Marks.
The model predicted Final_Marks for a new student.
R2 Score: 0.9847425924399397